// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo-server/pkg/pb/demo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClockEvent_Event int32

const (
	ClockEvent_START ClockEvent_Event = 0
	ClockEvent_TICK  ClockEvent_Event = 1
	ClockEvent_TOCK  ClockEvent_Event = 2
	ClockEvent_STOP  ClockEvent_Event = 3
)

var ClockEvent_Event_name = map[int32]string{
	0: "START",
	1: "TICK",
	2: "TOCK",
	3: "STOP",
}

var ClockEvent_Event_value = map[string]int32{
	"START": 0,
	"TICK":  1,
	"TOCK":  2,
	"STOP":  3,
}

func (x ClockEvent_Event) String() string {
	return proto.EnumName(ClockEvent_Event_name, int32(x))
}

func (ClockEvent_Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{9, 0}
}

type CreateTickerRequest struct {
	Interval             uint32   `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTickerRequest) Reset()         { *m = CreateTickerRequest{} }
func (m *CreateTickerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTickerRequest) ProtoMessage()    {}
func (*CreateTickerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{0}
}

func (m *CreateTickerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTickerRequest.Unmarshal(m, b)
}
func (m *CreateTickerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTickerRequest.Marshal(b, m, deterministic)
}
func (m *CreateTickerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTickerRequest.Merge(m, src)
}
func (m *CreateTickerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTickerRequest.Size(m)
}
func (m *CreateTickerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTickerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTickerRequest proto.InternalMessageInfo

func (m *CreateTickerRequest) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type CreateTickerResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTickerResponse) Reset()         { *m = CreateTickerResponse{} }
func (m *CreateTickerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTickerResponse) ProtoMessage()    {}
func (*CreateTickerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{1}
}

func (m *CreateTickerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTickerResponse.Unmarshal(m, b)
}
func (m *CreateTickerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTickerResponse.Marshal(b, m, deterministic)
}
func (m *CreateTickerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTickerResponse.Merge(m, src)
}
func (m *CreateTickerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTickerResponse.Size(m)
}
func (m *CreateTickerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTickerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTickerResponse proto.InternalMessageInfo

func (m *CreateTickerResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StopClockRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockRequest) Reset()         { *m = StopClockRequest{} }
func (m *StopClockRequest) String() string { return proto.CompactTextString(m) }
func (*StopClockRequest) ProtoMessage()    {}
func (*StopClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{2}
}

func (m *StopClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockRequest.Unmarshal(m, b)
}
func (m *StopClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockRequest.Marshal(b, m, deterministic)
}
func (m *StopClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockRequest.Merge(m, src)
}
func (m *StopClockRequest) XXX_Size() int {
	return xxx_messageInfo_StopClockRequest.Size(m)
}
func (m *StopClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockRequest proto.InternalMessageInfo

func (m *StopClockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StopClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockResponse) Reset()         { *m = StopClockResponse{} }
func (m *StopClockResponse) String() string { return proto.CompactTextString(m) }
func (*StopClockResponse) ProtoMessage()    {}
func (*StopClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{3}
}

func (m *StopClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockResponse.Unmarshal(m, b)
}
func (m *StopClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockResponse.Marshal(b, m, deterministic)
}
func (m *StopClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockResponse.Merge(m, src)
}
func (m *StopClockResponse) XXX_Size() int {
	return xxx_messageInfo_StopClockResponse.Size(m)
}
func (m *StopClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockResponse proto.InternalMessageInfo

type StopAllClocksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAllClocksRequest) Reset()         { *m = StopAllClocksRequest{} }
func (m *StopAllClocksRequest) String() string { return proto.CompactTextString(m) }
func (*StopAllClocksRequest) ProtoMessage()    {}
func (*StopAllClocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{4}
}

func (m *StopAllClocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAllClocksRequest.Unmarshal(m, b)
}
func (m *StopAllClocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAllClocksRequest.Marshal(b, m, deterministic)
}
func (m *StopAllClocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAllClocksRequest.Merge(m, src)
}
func (m *StopAllClocksRequest) XXX_Size() int {
	return xxx_messageInfo_StopAllClocksRequest.Size(m)
}
func (m *StopAllClocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAllClocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAllClocksRequest proto.InternalMessageInfo

type StopAllClocksResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAllClocksResponse) Reset()         { *m = StopAllClocksResponse{} }
func (m *StopAllClocksResponse) String() string { return proto.CompactTextString(m) }
func (*StopAllClocksResponse) ProtoMessage()    {}
func (*StopAllClocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{5}
}

func (m *StopAllClocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAllClocksResponse.Unmarshal(m, b)
}
func (m *StopAllClocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAllClocksResponse.Marshal(b, m, deterministic)
}
func (m *StopAllClocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAllClocksResponse.Merge(m, src)
}
func (m *StopAllClocksResponse) XXX_Size() int {
	return xxx_messageInfo_StopAllClocksResponse.Size(m)
}
func (m *StopAllClocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAllClocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopAllClocksResponse proto.InternalMessageInfo

func (m *StopAllClocksResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ListClocksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClocksRequest) Reset()         { *m = ListClocksRequest{} }
func (m *ListClocksRequest) String() string { return proto.CompactTextString(m) }
func (*ListClocksRequest) ProtoMessage()    {}
func (*ListClocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{6}
}

func (m *ListClocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClocksRequest.Unmarshal(m, b)
}
func (m *ListClocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClocksRequest.Marshal(b, m, deterministic)
}
func (m *ListClocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClocksRequest.Merge(m, src)
}
func (m *ListClocksRequest) XXX_Size() int {
	return xxx_messageInfo_ListClocksRequest.Size(m)
}
func (m *ListClocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClocksRequest proto.InternalMessageInfo

type ListClocksResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClocksResponse) Reset()         { *m = ListClocksResponse{} }
func (m *ListClocksResponse) String() string { return proto.CompactTextString(m) }
func (*ListClocksResponse) ProtoMessage()    {}
func (*ListClocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{7}
}

func (m *ListClocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClocksResponse.Unmarshal(m, b)
}
func (m *ListClocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClocksResponse.Marshal(b, m, deterministic)
}
func (m *ListClocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClocksResponse.Merge(m, src)
}
func (m *ListClocksResponse) XXX_Size() int {
	return xxx_messageInfo_ListClocksResponse.Size(m)
}
func (m *ListClocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClocksResponse proto.InternalMessageInfo

func (m *ListClocksResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type GetClockEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClockEventsRequest) Reset()         { *m = GetClockEventsRequest{} }
func (m *GetClockEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetClockEventsRequest) ProtoMessage()    {}
func (*GetClockEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{8}
}

func (m *GetClockEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClockEventsRequest.Unmarshal(m, b)
}
func (m *GetClockEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClockEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetClockEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClockEventsRequest.Merge(m, src)
}
func (m *GetClockEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetClockEventsRequest.Size(m)
}
func (m *GetClockEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClockEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClockEventsRequest proto.InternalMessageInfo

type ClockEvent struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event                ClockEvent_Event `protobuf:"varint,2,opt,name=event,proto3,enum=ClockEvent_Event" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClockEvent) Reset()         { *m = ClockEvent{} }
func (m *ClockEvent) String() string { return proto.CompactTextString(m) }
func (*ClockEvent) ProtoMessage()    {}
func (*ClockEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a2a938d1a22f51, []int{9}
}

func (m *ClockEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockEvent.Unmarshal(m, b)
}
func (m *ClockEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockEvent.Marshal(b, m, deterministic)
}
func (m *ClockEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockEvent.Merge(m, src)
}
func (m *ClockEvent) XXX_Size() int {
	return xxx_messageInfo_ClockEvent.Size(m)
}
func (m *ClockEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ClockEvent proto.InternalMessageInfo

func (m *ClockEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClockEvent) GetEvent() ClockEvent_Event {
	if m != nil {
		return m.Event
	}
	return ClockEvent_START
}

func init() {
	proto.RegisterEnum("ClockEvent_Event", ClockEvent_Event_name, ClockEvent_Event_value)
	proto.RegisterType((*CreateTickerRequest)(nil), "CreateTickerRequest")
	proto.RegisterType((*CreateTickerResponse)(nil), "CreateTickerResponse")
	proto.RegisterType((*StopClockRequest)(nil), "StopClockRequest")
	proto.RegisterType((*StopClockResponse)(nil), "StopClockResponse")
	proto.RegisterType((*StopAllClocksRequest)(nil), "StopAllClocksRequest")
	proto.RegisterType((*StopAllClocksResponse)(nil), "StopAllClocksResponse")
	proto.RegisterType((*ListClocksRequest)(nil), "ListClocksRequest")
	proto.RegisterType((*ListClocksResponse)(nil), "ListClocksResponse")
	proto.RegisterType((*GetClockEventsRequest)(nil), "GetClockEventsRequest")
	proto.RegisterType((*ClockEvent)(nil), "ClockEvent")
}

func init() { proto.RegisterFile("demo-server/pkg/pb/demo.proto", fileDescriptor_46a2a938d1a22f51) }

var fileDescriptor_46a2a938d1a22f51 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x61, 0x4b, 0xf2, 0x50,
	0x14, 0xc7, 0x9f, 0xa9, 0x7b, 0x70, 0x47, 0x94, 0x79, 0xdc, 0x4c, 0x06, 0x81, 0xec, 0x45, 0x89,
	0xe0, 0xd5, 0x8c, 0x08, 0x7a, 0x11, 0xc8, 0x8a, 0x08, 0x03, 0x63, 0xee, 0x0b, 0xa8, 0x1d, 0x42,
	0x9c, 0xdb, 0xda, 0x6e, 0xbe, 0xe9, 0xfb, 0xf4, 0x39, 0x63, 0x77, 0xa6, 0x4e, 0x2f, 0xbd, 0x91,
	0x73, 0xff, 0xf7, 0xef, 0x8f, 0xed, 0xfc, 0x06, 0xe7, 0x6f, 0xb4, 0x0e, 0x7b, 0x09, 0xc5, 0x1b,
	0x8a, 0xfb, 0xd1, 0xea, 0xbd, 0x1f, 0xcd, 0xfb, 0x69, 0xc4, 0xa2, 0x38, 0xe4, 0xa1, 0x7d, 0x05,
	0x0d, 0x27, 0xa6, 0x19, 0x27, 0x6f, 0xb9, 0x58, 0x51, 0xec, 0xd2, 0xc7, 0x27, 0x25, 0x1c, 0x2d,
	0x28, 0x2f, 0x03, 0x4e, 0xf1, 0x66, 0xe6, 0xb7, 0x94, 0xb6, 0xd2, 0xa9, 0xba, 0xbb, 0xb3, 0xdd,
	0x05, 0x23, 0xff, 0x97, 0x24, 0x0a, 0x83, 0x84, 0x10, 0xa1, 0x14, 0xcc, 0xd6, 0x24, 0xfa, 0x9a,
	0x2b, 0x66, 0xfb, 0x02, 0xf4, 0x29, 0x0f, 0x23, 0xc7, 0x0f, 0x17, 0xab, 0x5f, 0xb6, 0xac, 0xd7,
	0x80, 0xfa, 0x41, 0x2f, 0x03, 0xda, 0x4d, 0x30, 0xd2, 0x70, 0xe4, 0xfb, 0x22, 0x4f, 0xb6, 0x00,
	0xbb, 0x07, 0xe6, 0x51, 0xbe, 0x7d, 0x02, 0x03, 0xd4, 0x94, 0x96, 0xb4, 0x94, 0x76, 0xb1, 0xa3,
	0xb9, 0xd9, 0x21, 0x65, 0xbf, 0x2c, 0x13, 0x9e, 0x67, 0x74, 0x01, 0x0f, 0xc3, 0x3f, 0x01, 0x67,
	0x60, 0x3e, 0x51, 0x56, 0x7d, 0xdc, 0x50, 0xc0, 0x77, 0x90, 0x2f, 0x80, 0x7d, 0x2a, 0x7b, 0x2f,
	0xbc, 0x04, 0x95, 0xd2, 0xcb, 0x56, 0xa1, 0xad, 0x74, 0x6a, 0xc3, 0x3a, 0xdb, 0xf7, 0x99, 0xf8,
	0x75, 0xb3, 0x7b, 0x7b, 0x00, 0x6a, 0x46, 0xd1, 0x40, 0x9d, 0x7a, 0x23, 0xd7, 0xd3, 0xff, 0x61,
	0x19, 0x4a, 0xde, 0xb3, 0x33, 0xd6, 0x15, 0x31, 0x4d, 0x9c, 0xb1, 0x5e, 0x48, 0xa7, 0xa9, 0x37,
	0x79, 0xd5, 0x8b, 0xc3, 0xef, 0x02, 0x94, 0x1e, 0x68, 0x1d, 0xe2, 0x1d, 0x54, 0x32, 0x1f, 0x82,
	0x8d, 0x06, 0x93, 0x08, 0xb5, 0x4c, 0x26, 0x75, 0x36, 0x04, 0x6d, 0xb7, 0x77, 0xac, 0xb3, 0x63,
	0x57, 0x16, 0xb2, 0x13, 0x2d, 0x78, 0x0f, 0xd5, 0xdc, 0xfa, 0xd1, 0x64, 0x32, 0x4d, 0x56, 0x93,
	0xc9, 0x2d, 0xdd, 0x00, 0xec, 0x57, 0x8f, 0xc8, 0x4e, 0xe4, 0x58, 0x0d, 0x26, 0x71, 0x73, 0x0b,
	0xb5, 0xbc, 0x05, 0x6c, 0x32, 0xa9, 0x16, 0xab, 0x72, 0xb0, 0xe5, 0x81, 0x32, 0xff, 0x2f, 0xbe,
	0xf4, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0xa3, 0x32, 0xa5, 0x0a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	CreateClock(ctx context.Context, in *CreateTickerRequest, opts ...grpc.CallOption) (*CreateTickerResponse, error)
	StopClock(ctx context.Context, in *StopClockRequest, opts ...grpc.CallOption) (*StopClockResponse, error)
	StopAllClocks(ctx context.Context, in *StopAllClocksRequest, opts ...grpc.CallOption) (*StopAllClocksResponse, error)
	ListClocks(ctx context.Context, in *ListClocksRequest, opts ...grpc.CallOption) (*ListClocksResponse, error)
	GetClockEvents(ctx context.Context, in *GetClockEventsRequest, opts ...grpc.CallOption) (Demo_GetClockEventsClient, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) CreateClock(ctx context.Context, in *CreateTickerRequest, opts ...grpc.CallOption) (*CreateTickerResponse, error) {
	out := new(CreateTickerResponse)
	err := c.cc.Invoke(ctx, "/Demo/CreateClock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) StopClock(ctx context.Context, in *StopClockRequest, opts ...grpc.CallOption) (*StopClockResponse, error) {
	out := new(StopClockResponse)
	err := c.cc.Invoke(ctx, "/Demo/StopClock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) StopAllClocks(ctx context.Context, in *StopAllClocksRequest, opts ...grpc.CallOption) (*StopAllClocksResponse, error) {
	out := new(StopAllClocksResponse)
	err := c.cc.Invoke(ctx, "/Demo/StopAllClocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) ListClocks(ctx context.Context, in *ListClocksRequest, opts ...grpc.CallOption) (*ListClocksResponse, error) {
	out := new(ListClocksResponse)
	err := c.cc.Invoke(ctx, "/Demo/ListClocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) GetClockEvents(ctx context.Context, in *GetClockEventsRequest, opts ...grpc.CallOption) (Demo_GetClockEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Demo_serviceDesc.Streams[0], "/Demo/GetClockEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoGetClockEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Demo_GetClockEventsClient interface {
	Recv() (*ClockEvent, error)
	grpc.ClientStream
}

type demoGetClockEventsClient struct {
	grpc.ClientStream
}

func (x *demoGetClockEventsClient) Recv() (*ClockEvent, error) {
	m := new(ClockEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	CreateClock(context.Context, *CreateTickerRequest) (*CreateTickerResponse, error)
	StopClock(context.Context, *StopClockRequest) (*StopClockResponse, error)
	StopAllClocks(context.Context, *StopAllClocksRequest) (*StopAllClocksResponse, error)
	ListClocks(context.Context, *ListClocksRequest) (*ListClocksResponse, error)
	GetClockEvents(*GetClockEventsRequest, Demo_GetClockEventsServer) error
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) CreateClock(ctx context.Context, req *CreateTickerRequest) (*CreateTickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClock not implemented")
}
func (*UnimplementedDemoServer) StopClock(ctx context.Context, req *StopClockRequest) (*StopClockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopClock not implemented")
}
func (*UnimplementedDemoServer) StopAllClocks(ctx context.Context, req *StopAllClocksRequest) (*StopAllClocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAllClocks not implemented")
}
func (*UnimplementedDemoServer) ListClocks(ctx context.Context, req *ListClocksRequest) (*ListClocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClocks not implemented")
}
func (*UnimplementedDemoServer) GetClockEvents(req *GetClockEventsRequest, srv Demo_GetClockEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetClockEvents not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_CreateClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).CreateClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Demo/CreateClock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).CreateClock(ctx, req.(*CreateTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_StopClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).StopClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Demo/StopClock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).StopClock(ctx, req.(*StopClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_StopAllClocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAllClocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).StopAllClocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Demo/StopAllClocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).StopAllClocks(ctx, req.(*StopAllClocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_ListClocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).ListClocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Demo/ListClocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).ListClocks(ctx, req.(*ListClocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_GetClockEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetClockEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServer).GetClockEvents(m, &demoGetClockEventsServer{stream})
}

type Demo_GetClockEventsServer interface {
	Send(*ClockEvent) error
	grpc.ServerStream
}

type demoGetClockEventsServer struct {
	grpc.ServerStream
}

func (x *demoGetClockEventsServer) Send(m *ClockEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClock",
			Handler:    _Demo_CreateClock_Handler,
		},
		{
			MethodName: "StopClock",
			Handler:    _Demo_StopClock_Handler,
		},
		{
			MethodName: "StopAllClocks",
			Handler:    _Demo_StopAllClocks_Handler,
		},
		{
			MethodName: "ListClocks",
			Handler:    _Demo_ListClocks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClockEvents",
			Handler:       _Demo_GetClockEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "demo-server/pkg/pb/demo.proto",
}
